AllCops:
  TargetRubyVersion: 3.0

Layout/LineLength:
  Max: 100

Style/MutableConstant:
  Enabled: false

# Dumb, but also brand new.
Style/NumericPredicate:
  Enabled: false

# Allows for raising Redd::ResponseErrors with a Response object.
Style/RaiseArgs:
  Enabled: false

# Many reddit calls demand a lot of parameters.
Metrics/ParameterLists:
  CountKeywordArgs: false

# Stop rubocop from complaining about large `describe` blocks.
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

# Allow longer methods when they're well-structured and readable
Metrics/MethodLength:
  CountAsOne: [array, hash, heredoc, method_call]